### ISSUE TITLE
Getting a retrofit error when trying to run the advanced example project.

### ISSUE THREAD

**Issue by mnahro** [DroidsOnRoids/jspoon#14]
Hi, 
Im trying to run the advanced example module and I am getting the following error: 
```
Exception in thread "main" java.lang.NoClassDefFoundError: retrofit2/Retrofit
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:126)
Caused by: java.lang.ClassNotFoundException: retrofit2.Retrofit
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

Process finished with exit code 1
```

**Comment by burnoo** [comment]
This is not a problem with a library or an example itself, but with IDE (Android Studio or Intellij IDEA) -
libraries are not added to `classpath` correctly.
You can edit Run configuration and add `-classpath` parameter manually, but the simplier solution is to create JUnit4 Tests and run them:
```java
public class IntellijHelper {
    @Test
    public void startJava() {
        Example.main(new String[]{});
    }

    @Test
    public void startKotlin() {
        ExampleKt.main(new String[]{});
    }
}
```
I will try to find more elegant solution tomorrow.

**Comment by mnahro** [comment]
Thank you for looking into, I will try it today.
