### ISSUE TITLE
Proguard rules are not defined

### ISSUE THREAD

**Issue by centsol** [DroidsOnRoids/jspoon#71]
**Describe the bug**
CAn you please let me know what are the pro-guard rules?
**To Reproduce**
After applying I am getting following crash logs using retrofit
Feb 23, 2019 08:37 AM:RestCaller:java.lang.NoClassDefFoundError: org.jsoup.c.i$b
	at org.jsoup.c.f$a.<init>(Unknown Source:372)
	at org.jsoup.c.f.<init>(Unknown Source:19)
	at org.jsoup.d.m.b(Unknown Source:32)
	at org.jsoup.d.m.a(Unknown Source:42)
	at org.jsoup.d.b.a(Unknown Source:56)
	at org.jsoup.d.g.a(Unknown Source:100)
	at org.jsoup.a.a(Unknown Source:58)
	at pl.droidsonroids.jspoon.a.a(Unknown Source:58)
	at pl.droidsonroids.a.b.a(Unknown Source:17)
	at pl.droidsonroids.a.b.convert(Unknown Source:8)
	at retrofit2.ServiceMethod.toResponse(Unknown Source:119)
	at retrofit2.OkHttpCall.parseResponse(Unknown Source:218)
	at retrofit2.OkHttpCall$1.onResponse(Unknown Source:112)
	at okhttp3.x$a.c(Unknown Source:141)
	at okhttp3.internal.b.run(Unknown Source:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ExceptionInInitializerError
	... 18 more
Caused by: java.lang.IllegalStateException: Could not read resource entities-xhtml.properties. Make sure you copy resources for org.jsoup.c.i
	at org.jsoup.c.i.b(Unknown Source:301)
	at org.jsoup.c.i.a(Unknown Source:25)
	at org.jsoup.c.i$b.<init>(Unknown Source:53)
	at org.jsoup.c.i$b.<clinit>(Unknown Source:34)
	... 18 more

**Comment by koral--** [comment]
@centsol could you paste deobfuscated stacktrace?

`entities-xhtml.properties` should not be needed in the current version: https://github.com/jhy/jsoup/commit/f3035cafbbd8830de75f641920f8e5dbf0070f7c#diff-2ae1d9d6a9f9ee450c8a12116dc76658L39
so probably you are using older version of library.
